### PR TITLE
Update config template

### PR DESCRIPTION
**Pull request by jesserockz**
This puts the new settings and tidy ups from #17 into the template instead of the generated files.

The config.json files will be regenerated on next release

### CODE REVIEW

**Review by frenck — APPROVED** [review]
LGTM ✅ 

Sorry! Didn't know there was a generator 🤒

**Comment by ludeeus** [comment]
Closes https://github.com/esphome/issues/issues/1837

**Comment by TheZoker** [comment]
Closes https://github.com/esphome/hassio/issues/20

**Comment by jesserockz** [comment]
Yeah, I don't have write permission in this repo so cannot merge it and get another release out which will regenerate the files and push to the addons repo

**Pull request merged**
