### PR TITLE
Rename snapshot_exclude to backup_exclude

### PR DESCRIPTION
**Pull request by ludeeus**
Reviewer note:
Can be merged to dev now, but beta/stable should wait until a new supervisor version has been pushed to those same channels

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
LGTM :+1:

I see it's marked as a draft, is it ready to be merged?

**Comment by ludeeus** [comment]
It can be merged, but publishing beta/stable with this change should wait untill Supervisor 2021.08.0+ has been published to their respective channels
<https://version.home-assistant.io/beta.json>
<https://version.home-assistant.io/stable.json>

**Comment by jesserockz** [comment]
This might be tricky as I am about to release 1.20.2 which will auto generate the stable and beta configs from the template...
What are the consequences if this is released now?

**Comment by ludeeus** [comment]
It will log warnings for bad config, and it will not work as intended

**Comment by OttoWinter** [comment]
Oh.. ok I guess let's revert it for now?

**Comment by ludeeus** [comment]
yes https://github.com/esphome/hassio/pull/37

**Pull request merged**
